// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyProject1;

namespace ToyProject1.Migrations
{
    [DbContext(typeof(ToDosContext))]
    partial class ToDosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToyProject1.Models.ToDo", b =>
                {
                    b.Property<int>("ToDoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ToDoCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToDoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDoDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToDoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToDoStatus")
                        .HasColumnType("bit");

                    b.HasKey("ToDoID");

                    b.ToTable("ToDo");
                });
#pragma warning restore 612, 618
        }
    }
}
